# Generated by Django 2.2.6 on 2019-11-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191101_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='order',
            new_name='num_order',
        ),
    ]
