# Generated by Django 2.2.6 on 2019-11-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinbasket_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='session_key',
        ),
    ]
