# Generated by Django 2.2.6 on 2019-11-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
