# Generated by Django 2.2.6 on 2019-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20191025_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My subscriber', 'verbose_name_plural': 'My subscribers'},
        ),
    ]
